### PR TITLE
Improve desktop file

### PR DESCRIPTION
**Pull request by fgaz**
* Use valid spec version
* Add files exec argument
* Add RasterGraphics category
* Add mime types
* Add "Pixel Art" keyword

### CODE REVIEW

**Comment by bcampbell** [comment]
Wonderful, thank you!
Presumably it'd make sense to bump the v0.3 tag to include the new .desktop file? Not sure what github will do this with the existing 0.3 release already up... I could always add a 0.3.1 tag+release if simpler. Any thoughts?

**Comment by bcampbell** [comment]
cool - github _seems_ to have coped OK with the force-pushed retag! But let me know if you spot any oddness :-)

**Comment by bcampbell** [comment]
Doh!
Totally misread your comment.
OK. Old tag restored, new one added!

**Comment by fgaz** [comment]
Thanks!

**Comment by bcampbell** [comment]
Hmm. How odd.
I had thought that `operator!=` was implicitly provided when you provided an `operator==`... but the quick digging I've done just now hints that that might not be the case.
Except that all the compilers I've tried it on so far _do_ seem to provide `operator!=` implicitly ;-)
In any case, should be an easy fix, but I might not get a chance to do it for a day or so...

**Pull request merged**
