### PR TITLE
QT 5 conversion

### PR DESCRIPTION
**Pull request by caiwan**
Conversion to QT5 was done.

### CODE REVIEW

**Comment by bcampbell** [comment]
Thanks for that!
I've merged it into both the master branch, and the rgb branch (the rgb branch is what I'm working on at the moment, adding some basic support for using non-paletted images)

**Comment by caiwan** [comment]
I'm planning to make some changes in it; mainly making able to to handle muliple kind of projects, which could be choosen at the startup. I have an old pixel editor for C64, which can hadle interlaced hi-res, and mulicolor images. I want to integrate this into it, while the rest of the features will still available.

**Comment by bcampbell** [comment]
Fantastic!

May I recommend working off the RGB branch? I plan to merge that into master as soon as possible, so it'd be simpler to consider it as the current development branch and save hassle later.



I've often thought it'd be great to support assorted old-style modes (things like C64 multicolour mode with the fat pixels and colour restrictions).

Here's a bit of a brain dump of my thoughts on it so far - please feel free to ignore it!

I think it can be broken down into a few separate features:

1. Support non-square pixels. eg:
  * C64 multicolour (2x width)
  * Amiga hires (2x height))
2. Support restrictions upon colours in palette, eg:
  * fixed palette (eg CGA/EGA, fixed palette on C64/spectrum/whatever)
  * colour resolution restrictions (eg snap palette colours to 16 bit RGB 555,565,444, whatever)
  * Halfbright colours (second half of palette mirror of first half, but with modified brightness)
3. Special colour rules, eg:
  * C64, Spectrum: only 2 colours per 8x8 block
  * C64 multicolour: 2 fixed colours for whole image, 2 colours selectable per 8x8 block
  * amiga HAM mode (interpolated colour)
  * Whatever rules apply for fancy c64 interlaced hires (wow... I didn't realise how many techniques people have come up with!)

From these features you can support a whole bunch of retro hardware and oddball modes. Each mode would just activate whatever set of restrictions it needed.

I think 1 and 2 can be done pretty generally.
Number 3 is a little fiddlier. I'd imagine a system which invokes a check over any area which has been edited, and makes modifications to enforce whatever oddball-mode rules are active...

So if the only-two-colours-per-8x8-block rule was in force, and the user tries to draw in a third colour... then it would either:
 * have no effect
  * use the closest match of the 2 existing colours
  * replace one of the two existing colours in the block with the new one
What does your existing C64 pixel editor do in such cases?

**Comment by caiwan** [comment]
First of all, i'd like to add som minor features, for instance, separate libdevil, xpm and gif from the main project, and take them into an importer/exporter class. When none of them are available compile time, it can use an own native format. Also, do the same with the porjects. 
Also I'd like to implement (full) keyboard control, grid, etc.

**Comment by bcampbell** [comment]
I'm actually doing some work on libdevil at the moment, with evilpixie in mind.
The aim would be to remove all the annoying fileformat special cases from evilpixie, so the import/export class you mention could be a pretty thin layer.

I was aiming to avoid a "native" evilpixie format if possible. At most, I was thinking of using a custom chunk to slip evilpixie-specific data in to formats which allow it (eg png).

My plans for DevIL:
- clean up DevIL so I can easily build linux, mac and windows versions (building DevIL is a little fragile at the moment)
- support all the formats I want for evilpixie (ie xpm, better gif support, animated PNG etc etc...). This would remove a lot of crud code from evilpixie.
- add a method to query which formats are compiled, and what capabilities they have (eg multiple frames? paletted images? Alpha transparency? colour-key transparency?). This means evilpixie could check which suitable formats are available for saving in. At the moment evilpixie just has to try it and hope for the best...
- assorted bugfixes (eg sometimes getting the image upside down)

Regarding keyboard control, I've been using DPaint keys where obviously suitable, but just do whatever you think feels right!

**Comment by caiwan** [comment]
Before we start doing anything serious, I'd consider to set up a testing and/or continous integration, code coverage system somewhere, to make sure if everything is working as it suposed to. 

My plans were:
- format support was meant to handle by the porject class.  Create a base class, and have various pure virtuals for them, e.g. `isHaveFrames()` or `isHaveScreens()` for C64 interlace; and have a class and do the same for the pixel formats, and take an abstract factroy into the Project class ``
- For functionality, I'd take features from [Timanthes](http://csdb.dk/release/?id=75871), which was written in C#/.NET, very buggy, and closed source; For instance the native code exporter for (real) C64.

**Comment by bcampbell** [comment]
Thanks for the Timanthes link - I've had a little play with it to see how it manages the various wacky limitations of the fancier C64 modes.
I'm going to open up some issues to track some of this stuff separately rather than tangle up the different topics.

**Pull request merged**
